### ISSUE TITLE
How to run the provided go files?

### ISSUE THREAD

**Issue by sanderjo** [andrewstuart/go-nzb#2]
```
$ go run nzb_test.go 
go run: cannot run *_test.go files (nzb_test.go)
```

```
$ go run nzb.go
go run: cannot run non-main package
```

**Comment by andrewstuart** [comment]
Sorry for the lack of documentation/readme. This particular package is just intended to be a library that provides NZB structs useful for unmarshalling NZB files.

Really, I've only implemented what I found necessary in order to locate the appropriate files on usenet (for example in my half-baked [dlite](/andrewstuart/dlite) usenet client). I'm fairly certain it would fail hard if you attempted to marshal a struct into a valid NZB file.

**Comment by andrewstuart** [comment]
Hopefully that gives you a little more information. If you're looking for something runnable, you could definitely check out dlite, as linked before. It's pretty specific to my use case since it's half abandoned, but you're definitely free to check it out if only for examples.

**Comment by sanderjo** [comment]
OK, I'll check https://github.com/andrewstuart/dlite.git

Thanks
